services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

volumes:
  rubygems: