databases:
  - name: postgres
    ipAllowList: []
    databaseName: blog
    user: blog
    plan: free

services:
  - type: web
    name: blog
    env: ruby
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
